[package]
name = "todoistctl"
version = "0.4.0"
edition = "2021"
authors = ["Balazs Nadasdi <efertone@pm.me>"]
license = "Apache-2.0 AND MIT"
homepage = "https://github.com/yitsushi/todoist-rs"
repository = "https://github.com/yitsushi/todoist-rs"
description = "Todoist CLI"
readme = "README.md"
keywords = ["todoist", "todo", "task", "project", "todoist"]
categories = ["data-structures", "web-programming::http-client"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
confy = { version = "0.6.0", features = ["ron", "ron_conf"], default-features = false }
serde = { version = "1.0.196", features = ["derive"] }
libtodoist = { path = "../../lib/libtodoist/", version = "0.4.0" }
tokio = { version = "1.35.1", features = ["full"] }
