[package]
name = "todoistctl"
version = "0.2.0"
edition = "2021"
authors = ["Balazs Nadasdi <efertone@pm.me>"]
license = "Apache-2.0 AND MIT"
homepage = "https://github.com/yitsushi/todoist-rs"
repository = "https://github.com/yitsushi/todoist-rs"
description = "Todoist CLI"
readme = "README.md"
keywords = ["todoist", "todo", "task", "project", "todoist"]
categories = ["data-structures", "web-programming::http-client"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.25", features = ["derive"] }
confy = { version = "0.5.1", features = ["ron", "ron_conf"], default-features = false }
serde = { version = "1.0.147", features = ["derive"] }
libtodoist = { path = "../../lib/libtodoist/" }
tokio = { version = "1.21.2", features = ["full"] }
