[package]
name = "todoist-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.25", features = ["derive"] }
confy = { version = "0.5.1", features = ["ron", "ron_conf"], default-features = false }
serde = { version = "1.0.147", features = ["derive"] }
todoist = { path = "../../lib/todoist" }
tokio = { version = "1.21.2", features = ["full"] }
